apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: app-deployment
spec:
  selector:
    matchLabels:
      app: app
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: ramsundar07/app # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7070 # The port that the container is running on in the cluster


---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: app-k8ssvc
spec:
  selector:
    app: app
  ports:
    - protocol: "TCP"
      port: 7070 # The port that the service is running on in the cluster
      targetPort: 7070 # The port exposed by the service
  type: NodePort # type of the service.